SilverStripe\CMS\Model\SiteTree:
  extensions:
    - MetaTitleExtension
MetaTitleExtension:
  InsertBefore: MetaDescription
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
Unclecheese\EventCalendar\Calendar:
  extensions:
    - CalendarExtension
Unclecheese\EventCalendar\CalendarEvent:
  extensions:
    - CalendarEventExtension
