SiteTree:
  extensions:
    - MetaTitleExtension
MetaTitleExtension:
  InsertBefore: 'MetaDescription'
SiteConfig:
  extensions:
    - SiteConfigExtension
Calendar:
  extensions:
    - CalendarExtension
CalendarEvent:
  extensions:
    - CalendarEventExtension