SilverStripe\CMS\Model\SiteTree:
  extensions:
    - MetaTitleExtension
MetaTitleExtension:
  InsertBefore: MetaDescription
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
Calendar:
  extensions:
    - CalendarExtension
CalendarEvent:
  extensions:
    - CalendarEventExtension
